services:

  nextcloud-web:
    container_name: nc-web
    image: nginx:stable-perl
    restart: always
    networks:
      - nc_net
      - proxy
    depends_on:
      - redis
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`${DOMAIN}`)"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect,nextcloud_redirect"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
      - "traefik.http.services.nextcloud.loadbalancer.server.scheme=https"
      - "traefik.docker.network=proxy"
      - "traefik.http.middlewares.nextcloud-secure.headers.customFrameOptionsValue=ALLOW-FROM https://${ROOT_DOMAIN}"
      - "traefik.http.middlewares.nextcloud-secure.headers.contentSecurityPolicy=frame-ancestors 'self' ${ROOT_DOMAIN} *.${ROOT_DOMAIN}"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=/remote.php/dav/"
      - "traefik.http.routers.nextcloud-secure.middlewares=nextcloud_redirect"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./nc_data:/var/www/html
      - ./ssl:/etc/ssl/nginx

# NEXTCLOUD-FPM
  nextcloud:
    container_name: nc-fpm
    image: nextcloud:production-fpm
    restart: always
    networks:
      - nc_net
    depends_on:
      - redis
      - db
    environment:
      MYSQL_DB_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_HOST: "nc-db"
      MYSQL_PORT: "3306"
      REDIS_HOST_PASSWORD: "${REDIS_HOST_PASSWORD}"
      REDIS_HOST: "nc-redis"
      OVERWRITEHOST: "${DOMAIN}"  
      NEXTCLOUD_DATA_DIR: "${NC_DATA_DIR}"
      PHP_MEMORY_LIMIT: "${PHP_MEMORY_LIMIT}"
      PHP_UPLOAD_LIMIT: "${PHP_UPLOAD_LIMIT}"
      NEXTCLOUD_TRUSTED_DOMAINS: "${DOMAIN}"
      TRUSTED_PROXIES: "${TRUSTED_PROXIES}"
      OVERWRITEPROTOCOL: "https"
      OVERWRITE.CLI.URL: "https://${DOMAIN}"
    secrets:
      - db_name
      - db_user
      - db_password
    volumes:
      - ./nc_data:/var/www/html

# DATABASE
  db:
    container_name: nc-db
    hostname: nc-db
    image: mariadb:10.6
    restart: always
    networks:
      - nc_net
    environment:
      MARIADB_DB_FILE: /run/secrets/db_name
      MARIADB_USER_FILE: /run/secrets/db_user
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_name
      - db_user
      - db_password
      - db_root_password
    volumes:
      - ./mariadb_data:/var/lib/mysql

# REDIS CACHE
  redis:
    container_name: nc-redis
    image: redis:alpine3.20
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_HOST_PASSWORD}"]
    networks:
      - nc_net
    volumes:
      - ./redis_data:/data

# SECRETS
secrets:
  db_name:
    file: .secrets/DB_NAME
  db_user:
    file: .secrets/DB_USER
  db_password:
    file: .secrets/DB_PASSWORD
  db_root_password:
    file: .secrets/DB_ROOT_PASSWORD
  redis_host_password:
    file: .secrets/REDIS_HOST_PASSWORD

# NETWORK
networks:
  nc_net:
    driver: local
  proxy:
    external: true
